name: Update Build Date

on:
  push:
    branches:
      - dev
      - main

permissions: write-all

jobs:
  update_build_date:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Verify PAT Secret
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        if [ -z "${ACTIONS_PAT}" ]; then
          echo "Error: Unable to find the PAT secret for permissions."
          exit 1
        fi

    - name: Update build date
      run: |
        echo -n "Before: " && grep "^__build_date__" quiz/__init__.py
        current_date=$(date +'%Y-%m-%d-%H-%M-%S')
        sed -i "s/__build_date__ = .*/__build_date__ = '$current_date'/g" quiz/__init__.py
        echo -n "After:  " && grep "^__build_date__" quiz/__init__.py

    - name: Commit and push build date update
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        if [ -z "${ACTIONS_PAT}" ]; then
          echo "Error: Aborting with missing PAT secret."
          exit 1
        fi
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add quiz/__init__.py
        git commit -m "Update build date to $current_date"
        git push https://x-access-token:${ACTIONS_PAT}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

